/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionsPanel: typeof import('./src/components/ActionsPanel.vue')['default']
    AutostopPanel: typeof import('./src/components/AutostopPanel.vue')['default']
    BansPanel: typeof import('./src/components/BansPanel.vue')['default']
    ConfigEditorPanel: typeof import('./src/components/ConfigEditorPanel.vue')['default']
    LogPanel: typeof import('./src/components/LogPanel.vue')['default']
    PlayersPanel: typeof import('./src/components/PlayersPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
    UApp: typeof import('./../node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  }
}
